Feature/pra 35
MariaShamonova/practicum-game pull request #14
Opened 2023-05-05 13:58 UTC by MariaShamonova

<img width="1428" alt="Снимок экрана 2023-05-05 в 16 57 46" src="https://user-images.githubusercontent.com/39432525/236478346-a27152fe-adfc-4247-9e0a-466cd2edee7b.png">

Написала механику игры.

2023-05-06 12:23 UTC, lilylilps approved these changes

2023-05-08 12:04 UTC, MikeDevice requested changes

2023-05-08 12:04 UTC, MikeDevice commented on .DS_Store
Такое лучше в гитигноре кидать

2023-05-08 12:04 UTC, MikeDevice commented on packages/client/src/App.tsx
> +  return <div className={ `app ${ isDarkTheme ? DARK_THEME : LIGHT_THEME }` }>
Тут удобнее использовать либу classnames, но как хочешь)

2023-05-08 12:04 UTC, MikeDevice commented on packages/client/src/assets/theme/light.less
> +  //background-color: var(@sui-global_background);
Может вообще удалить?

2023-05-08 12:04 UTC, MikeDevice commented on packages/client/src/hooks/usePrevious.ts
> +export default usePrevious;
Название хука не особо понятное. Previous что? Значение? Роут? Картинка? И тд. Лучше бы как-то попонятнее назвать

2023-05-08 12:04 UTC, MikeDevice commented on packages/client/src/layout/header/styles.less
> +      cursor: pointer !important;
Обычно импортанты означают, что стили написаны неверно. Почему пришлось написать? Можно как-то иначе?

2023-05-08 12:04 UTC, MikeDevice commented on packages/client/src/pages/game/types.tsx
> +     info = 'info',
Выравнивание поправь

2023-05-08 12:04 UTC, MikeDevice commented on packages/client/src/pages/game/models/Queue.tsx
> +}
Прикольно. Ты изучала структуры данных?

2023-05-08 12:04 UTC, MikeDevice commented on packages/client/src/pages/game/models/Players.tsx
> +    for (let index = 0; index < users.length; index++) {
Циклы зло. Лучше итераторы. Заюзай тут map

2023-05-08 12:04 UTC, MikeDevice commented on packages/client/src/pages/game/models/Players.tsx
> +    return players.find((player: Player) => player.user.id === id) || {} as Player
Возвращать пустой объект как игрока -- очень плохо. Давай null тут возвращать?

2023-05-08 12:04 UTC, MikeDevice commented on packages/client/src/pages/game/models/Player.tsx
> +        this.cardOnHand = {} as CardType
Это неправильно. Ты просто обманываешь тут ТС. Давай инициализировать в null?

2023-05-08 12:04 UTC, MikeDevice commented on packages/client/src/pages/game/Game.tsx
> +  const [ players, setPlayers ] = useState(Players.init(users, (player: Player, index: number) => {
Чтобы не выполнять эту логику на каждый рендер, просто оберни в функцию useState(() => {...})

2023-05-08 12:04 UTC, MikeDevice commented on packages/client/src/pages/game/Game.tsx
> +
Тут что-то не то. Ты каждый рендер компонента будешь инициализировать очередь и бегать по циклу. Это неправильно и неэффективно

2023-05-08 12:04 UTC, MikeDevice commented on packages/client/src/pages/game/Game.tsx
> +    canvasRef.current?.addEventListener('click', (event) => {
Вешаешь обработчик, но нигде от него не отписываешься

2023-05-08 12:04 UTC, MikeDevice commented on packages/client/src/pages/game/Game.tsx
> +    if (rival.cardOnHand.value === 7 || rival.isProtect) {
Магическое число. Вынеси в константы. Рекомендую почитать про магические числа в программировании

2023-05-10 15:51 UTC, MikeDevice approved these changes
Не удалила DS store? Реши, нужен он или нет. Я уверен, что нет. И лей

2023-05-10 17:05 UTC, merged