Feature/pra 17
MariaShamonova/practicum-game pull request #16
Opened 2023-05-06 20:48 UTC by alexTaraskina

Логика авторизации и регистрации

![image](https://user-images.githubusercontent.com/20871455/236645919-dd77dd28-a52c-49b4-8833-55fbe5325a5e.png)

2023-05-07 13:27 UTC, lilylilps commented on packages/client/src/pages/login/Login.tsx
> +    return <Navigate replace to="/" />;
Думаю, надо сразу на /game/start редиректить

2023-05-07 13:27 UTC, lilylilps commented on packages/client/src/pages/home/Home.tsx
> +    if (!isAuth()) {
Мне кажется, эту страницу надо, наоборот, показывать неавторизованным пользователям) иначе как пользователи узнают, что это за игра, и зачем им вообще тогда заходить/регистрироваться

2023-05-07 13:37 UTC, lilylilps commented
![image](https://user-images.githubusercontent.com/86557654/236680823-c326801c-6e42-4cc5-840e-b327faea3095.png)

нажала на Нет аккаунта, чтобы зарегистрироваться
https://practicum-game-client-h2qohqlc2-mariashamonova.vercel.app/registration

2023-05-07 15:51 UTC, lilylilps commented
![image](https://user-images.githubusercontent.com/86557654/236688165-47bec5ad-d073-4b76-a92f-ce8a3c028463.png)

У нас вроде все на русском будет сделано, так что, думаю, ошибки валидации тоже лучше перевести)
(но даже если на англе, то после should просто contain))

2023-05-07 15:51 UTC, lilylilps approved these changes

2023-05-08 13:18 UTC, MikeDevice requested changes
сделать HOC

2023-05-08 13:18 UTC, MikeDevice commented on packages/client/src/pages/forum/Forum.tsx
> +  }
это надо делать HOC-ом, чтобы не делать такие ифаки на каждой странице.

2023-05-08 13:18 UTC, MikeDevice commented on packages/client/src/pages/profile/Profile.tsx
> +                //props.setAuthenticated(false);
удалить?

2023-05-08 13:18 UTC, MikeDevice commented on packages/client/src/pages/registration/Registration.tsx
> +    if (!loginError && !emailError && !nameError && !secondNameError && !phoneError && !passwordError) {
```suggestion
    if ([loginError, emailError, nameError, secondNameError, phoneError, passwordError].some(Boolean)) {
```

так проще вроде как

2023-05-08 17:15 UTC, alexTaraskina commented on packages/client/src/pages/forum/Forum.tsx
> +  }
@MikeDevice поправила, спасибо!

2023-05-09 08:51 UTC, MikeDevice approved these changes
Четко!

2023-05-09 15:54 UTC, merged