Feature/pra 38
MariaShamonova/practicum-game pull request #22
Opened 2023-05-18 10:49 UTC by MariaShamonova

Сделала полный цикл игры

2023-05-21 20:52 UTC, lilylilps approved these changes
Созванивались с Машей, обсуждали сделанную задачу, игра работает с небольшими недочетами, нужно будет поправить на неделе доработок :)

2023-05-23 08:33 UTC, MikeDevice requested changes
1. Вынеси пожалуйста логику игры из реакт компонента в хук (или еще лучше в обычный TS класс, но это уже по желанию). Так ты сможешь куда проще менять визуал игры, не трогая логику (так более верно с точки зрения архитектуры)

2. Постарайся, пожалуйста, в рамках ПР не рефакторить код, не относящийся к твоей задачи. У тебя в данном ПР много таких файлов есть и они пораждают две проблемы: сложно ревьюить код, увеличивается вероятность появления конфликтов с другими ПР

2023-05-23 08:33 UTC, MikeDevice commented on packages/client/src/hooks/useLocalStorage.ts
> +    }
Классный хук

2023-05-23 08:33 UTC, MikeDevice commented on packages/client/src/pages/game/Game.tsx
> +  const [activePlayer, setActivePlayer] = useState<Player>({} as Player)
Тут лучше в качестве начального значения null делать. Так более явно будет, ну и приводить тип пустого объекта не продется

2023-05-23 08:33 UTC, MikeDevice commented on packages/client/src/pages/game/Game.tsx
> +    websocket?.addEventListener('open', () => {
Подписку на сокет лучше реализовать в хуке. Так будет более изолированно. А сейчас просто получается, что твой компонент жестко зависит от технологии передачи данных (от сокета), а компоненты -- это View, если говорить в терминах архитектуры MVC и прочих подходов

2023-05-26 21:02 UTC, MariaShamonova commented
Вынесла состояние игры в Redux и логику в класс, еще раз прошла весь цикл игры и поправила все ошибки в логике, которые были

2023-05-28 07:33 UTC, MikeDevice approved these changes

2023-05-29 09:08 UTC, merged