PRA-43: set up Redux
MariaShamonova/practicum-game pull request #26
Opened 2023-05-20 13:56 UTC by lilylilps

### Прикрутила редакс и вынесла всю работу с состоянием приложения и апи в стор

### На неделе доработок постараюсь доделать обработку ошибок (сделать тостеры), добавить лоадеры и вынести диалог в отдельный компонент, чтобы уменьшить копипасту

2023-05-20 13:59 UTC, lilylilps commented on packages/client/src/pages/gameStart/GameStart.tsx
> +                // navigate(`/rooms/${res.id}`)
текущее апи чатов не позволяет получить информацию о чате по его id, чтобы внутри комнаты определить ее автора или ее название
пофиксим эти моменты, когда будем делать апи форума и создадим мини-табличку для хранения инфы о выбранном чате по id

2023-05-20 14:42 UTC, MariaShamonova approved these changes

2023-05-22 07:14 UTC, MikeDevice requested changes
унести бизнес логику из компонентов в контроллеры (это может быть скорее всего у тебя thunk)

2023-05-22 07:14 UTC, MikeDevice commented on packages/client/src/App.tsx
> +      .finally(() => setLoading(false))
такое лучше выносить из вьюхи в контроллер

2023-05-22 07:14 UTC, MikeDevice commented on packages/client/src/App.tsx
> +      .finally(() => setLoading(false))
я имею ввиду про finally и setLoading, тут важно не размазывать в компонентах причину установления лоадеров и тд

2023-05-22 07:14 UTC, MikeDevice commented on packages/client/src/App.tsx
> +      .finally(() => setLoading(false))
идеально из селекторов получать

```
const isLoading = useSelector(isAppLoading)
```

или что-то такое

2023-05-22 07:14 UTC, MikeDevice commented on packages/client/src/layout/header/MainHeader.tsx
> +      })
то же самое, что и писал выше. такое нужно в редаксе делать.

dispatch(actionStart)
dispatch(actionFail)
dispatch(actionLoading)

и загрузки

useSelector(isLoading)
useSelector(isFail)
useSelector(isSuccess)

таким образом компонент вообще не будет про причины появления разных штук в компонентах

2023-05-22 07:14 UTC, MikeDevice commented on packages/client/src/pages/gameStart/GameStart.tsx
> -// import { withAuthorizationCheck } from '../../utils/authorizedPage';
удалить?

2023-05-22 08:22 UTC, lilylilps commented on packages/client/src/layout/header/MainHeader.tsx
> +      })
а как можно navigate вынести в редакс, если это хук, а хуки можно только внутри компонентов вызывать?

2023-05-22 08:35 UTC, lilylilps commented on packages/client/src/pages/gameStart/GameStart.tsx
> -// import { withAuthorizationCheck } from '../../utils/authorizedPage';
это уже раскомментировано выше (17 строка)
оранжевым красятся строчки, которые были удалены

2023-05-22 11:45 UTC, MikeDevice commented on packages/client/src/layout/header/MainHeader.tsx
> +      })
не не не. не спорю. 

тут мы о разном. с точки зрения работоспособности -- ты умничка, всё чётко. Тут проблема в разделении кода. Не зря же придумал и разные MVC подходы и тд. Так вот все эти подходы про то, что View не должна много знать. И ты, когда делаешь такие резолвы, ты как бы зашиваешь слишком много инфы во Вью.

2023-05-22 11:46 UTC, MikeDevice approved these changes

2023-05-22 12:00 UTC, lilylilps commented on packages/client/src/layout/header/MainHeader.tsx
> +      })
Ага, поняла
Спасибо большое, учту!)

2023-05-22 12:01 UTC, merged