PRA-57 add Geolocation API
MariaShamonova/practicum-game pull request #33
Opened 2023-06-06 10:45 UTC by yugld

Добавить WEB API: Geolocation API

2023-06-09 10:33 UTC, yugld commented on packages/client/src/pages/thread/Thread.tsx
> +        if (!geolocationAPI) {
удалить логи полсе проверки

2023-06-11 09:04 UTC, MariaShamonova approved these changes

2023-06-13 10:41 UTC, MikeDevice requested changes

2023-06-13 10:41 UTC, MikeDevice commented on packages/client/src/pages/thread/Thread.tsx
> +    }
вот это неправильно, что определение геопозиции лежит внутри компонента. Грубо говоря, если тебе придётся ещё где-то определять геопозицию, то код отсюда придётся копипастить. Чтобы этого избежать, нужно вынести это в утилиты, и заюзать эту утилиту тут

2023-06-14 11:37 UTC, MikeDevice approved these changes

2023-06-15 09:58 UTC, merged