add profile page, userApi, edit user`s info
MariaShamonova/practicum-game pull request #9
Opened 2023-05-01 00:44 UTC by yugld

Добавлена страница пользователя — страница с информацией о пользователе, возможностью загрузить и сменить аватар, изменить пароль. Также добавлена возможность работы с UserAPI.

Ссылка на видео работы приложения https://disk.yandex.ru/i/23TjSlGvJIorkw

![image](https://user-images.githubusercontent.com/95404861/235384215-d50b2791-da56-483b-8c1d-42bd0a2bf34c.png)

2023-05-01 00:56 UTC, yugld commented
По сути созданы файлы fprofile.tsx, editPassword.tsx + папка c файлами src/api. Остальное все - npm formatter...

2023-05-01 10:10 UTC, lilylilps commented
![telegram-cloud-photo-size-2-5368532425501689612-y](https://user-images.githubusercontent.com/86557654/235439011-e19efeb0-3743-45ff-9f94-86d069e2a709.jpg)

кажется, display_name чуть съехал от центра, и мб можно между инпутами побольше отступ сделать

2023-05-01 10:12 UTC, lilylilps commented
![telegram-cloud-photo-size-2-5368532425501689614-y](https://user-images.githubusercontent.com/86557654/235439150-cc9ef31d-ad06-4caf-9540-7aad4b3baa2e.jpg)

очепятка)
и при закрытии модалки хорошо бы чистить инпуты, а то введенные данные там так и остаются, даже после смены пароля

2023-05-01 10:13 UTC, lilylilps commented
![telegram-cloud-photo-size-2-5368532425501689615-y](https://user-images.githubusercontent.com/86557654/235439300-e8cd5e2b-5499-412f-a0c9-fb2789480406.jpg)

можно, наверное, потом, но тогда не забыть сделать обработку ошибок, а то сейчас ничего не происходит

2023-05-01 10:14 UTC, lilylilps commented on package.json
> +    "react-hook-form": "^7.43.9"
А это где-то используется? Вообще вроде удобная штука для управления формой, но не заметила ее применения дальше по коду

2023-05-01 10:14 UTC, lilylilps commented on packages/client/src/components/EditPassword/EditPassword.tsx
> +  const handleSubmit = (event: any) => {
Наверное, лучше типизировать событие более конкретно

2023-05-01 10:14 UTC, lilylilps commented on packages/client/src/pages/profile/Profile.tsx
> +    const [phone, setPhone] = useState('')
Мне кажется, лучше сделать какое-то общее состояние формы в виду объекта и обновлять просто поля этого объекта по ключу (тогда можно будет и верстке ниже выводить инпуты в цикле, они же вроде все аналогичные, кроме названия поля, ну и значения)

Иначе если, допустим, придется добавить в форму еще там 10 полей, будет совсем неудобно управлять всем этим

2023-05-01 10:14 UTC, lilylilps commented on packages/client/src/pages/profile/Profile.tsx
> +                            required></TextField>
Если между открывающим и закрывающим тегом ничего нет, можно в конце открывающего просто ```/>```

2023-05-01 11:57 UTC, yugld commented on package.json
> +    "react-hook-form": "^7.43.9"
Для валидации хотела, но эпик другой - не стала трогать... удалила пока

2023-05-01 11:58 UTC, yugld commented on packages/client/src/components/EditPassword/EditPassword.tsx
> +  const handleSubmit = (event: any) => {
Спасибо, исправила!

2023-05-01 12:07 UTC, yugld commented on packages/client/src/pages/profile/Profile.tsx
> +    const [phone, setPhone] = useState('')
Не стала еще одну форму делать, потому что у нас одна уже есть и пришлось бы переделывать вместе с ней регистрацию и авторизацию. Решила пока не трогать и дождаться Саши. Тем более это самая большая форма у нас...

2023-05-01 12:13 UTC, yugld commented
> 



> ![telegram-cloud-photo-size-2-5368532425501689615-y](https://user-images.githubusercontent.com/86557654/235439300-e8cd5e2b-5499-412f-a0c9-fb2789480406.jpg)
> 
> можно, наверное, потом, но тогда не забыть сделать обработку ошибок, а то сейчас ничего не происходит

Вывела в алерт, вместо консоли, хотя пока без валидации удобнее было в консоли ошибки отслеживать..

2023-05-01 12:15 UTC, yugld commented
> ![telegram-cloud-photo-size-2-5368532425501689614-y](https://user-images.githubusercontent.com/86557654/235439150-cc9ef31d-ad06-4caf-9540-7aad4b3baa2e.jpg)
> 
> очепятка) и при закрытии модалки хорошо бы чистить инпуты, а то введенные данные там так и остаются, даже после смены пароля

Исправила - инпуты теперь чистятся после закрытия модального окна:)

2023-05-01 12:24 UTC, lilylilps approved these changes

2023-05-03 08:11 UTC, MikeDevice requested changes
1. вопросы в комментах
2. оставленные логи

поправить эти моменты и всё. в целом ПР прекрасный!

2023-05-03 08:11 UTC, MikeDevice commented on packages/client/vite.config.ts
> +  },
старайтесь затрагивать другие файлы в проекте в рамках своей задачи. иначе дифф получается огромным и непонятно, что конкретно менялось.

2023-05-03 08:11 UTC, MikeDevice commented on packages/client/src/api/BaseApi.ts
> +      timeout: 3000,
очень круто было бы, если ты таймаут можно было задавать параметром, а дефолт был бы 3000. Более гибко бы вышло

2023-05-03 08:11 UTC, MikeDevice commented on packages/client/src/api/BaseApi.ts
> +  }
как интересно

2023-05-03 08:11 UTC, MikeDevice commented on packages/client/src/api/userApi.ts
> +    super('https://ya-praktikum.tech/api/v2')
вот этот урл нужно унести внутрь базового апи, а то так выходит, что тебе придётся каждый раз в конструкторе каждого потомка его писать.

2023-05-03 08:11 UTC, MikeDevice commented on packages/client/src/api/BaseApi.ts
> +    this.instance = axios.create({
я бы это поле назвал `api`. Потому что в местах использования не сразу понятно, что за `instance`

2023-05-03 08:11 UTC, MikeDevice commented on packages/client/src/components/EditPassword/EditPassword.tsx
> +    console.log({ newPassword })
забыла удалить?)

2023-05-03 08:11 UTC, MikeDevice commented on packages/client/src/components/EditPassword/EditPassword.tsx
> +      .editPassword({ newPassword, oldPassword } as ChangePasswordData)
хммм. а почему тип приводишь. он же воответствует описанию интерфейса ChangePasswordData?

2023-05-03 08:11 UTC, MikeDevice commented on packages/client/src/components/EditPassword/EditPassword.tsx
> +        alert(`change password ${newPassword}`)
это временное?

2023-05-03 08:11 UTC, MikeDevice commented on packages/client/src/components/EditPassword/EditPassword.tsx
> +        alert(`change password ${newPassword}`)
немного душноты в чат 😄 : алерт сообщает о том, что пароль изменён:

```diff
- `change password ${newPassword}`
+ `password changed ${newPassword}`
```

2023-05-03 08:11 UTC, MikeDevice commented on packages/client/src/components/EditPassword/EditPassword.tsx
> +              onChange={e => setOldPassword(e.target.value)}
давай не будем делать инлайновые функции?) это является антипаттерном, так как их потом сложно редактировать, если придётся добавить новых строчек или же добавлять мемоизацию

2023-05-03 08:11 UTC, MikeDevice commented on packages/client/src/components/EditPassword/EditPassword.tsx
> +              onChange={e => setNewPassword(e.target.value)}
и тут

2023-05-03 08:11 UTC, MikeDevice commented on packages/client/src/pages/profile/Profile.tsx
> +            } as TUserOmit)
тот же вопрос про приведение типов

2023-05-03 10:14 UTC, yugld commented on packages/client/vite.config.ts
> +  },
Спасибо! Теперь форматер буду отдельным ПР запускать:)

2023-05-03 11:14 UTC, yugld commented on packages/client/src/components/EditPassword/EditPassword.tsx
> +      .editPassword({ newPassword, oldPassword } as ChangePasswordData)
Тут должен был быть также омит, исключающий строку повторения нового пароля. Сделала без нее, поэтому удаляю.

2023-05-03 12:01 UTC, yugld commented on packages/client/src/api/BaseApi.ts
> +      timeout: 3000,
Спасибо, исправила!

2023-05-03 12:02 UTC, yugld commented on packages/client/src/api/BaseApi.ts
> +  }
В комментариях на документацию ссылку оставила...

2023-05-03 12:03 UTC, yugld commented on packages/client/src/api/userApi.ts
> +    super('https://ya-praktikum.tech/api/v2')
Унесла:)

2023-05-03 12:03 UTC, yugld commented on packages/client/src/api/BaseApi.ts
> +    this.instance = axios.create({
Переименовала

2023-05-03 12:06 UTC, yugld commented on packages/client/src/components/EditPassword/EditPassword.tsx
> +    console.log({ newPassword })
Нет, оставила, чтобы на место логов и алертов в другом эпике выводить уведомления... А то неясно изменилось что-то или нет

2023-05-03 12:07 UTC, yugld commented on packages/client/src/components/EditPassword/EditPassword.tsx
> +        alert(`change password ${newPassword}`)
Да, чуть выше ответила про логи и алерты

2023-05-03 12:09 UTC, yugld commented on packages/client/src/components/EditPassword/EditPassword.tsx
> +              onChange={e => setOldPassword(e.target.value)}
Исправила, вынесла отдельно функцией handleChange

2023-05-03 12:11 UTC, yugld commented on packages/client/src/pages/profile/Profile.tsx
> +            } as TUserOmit)
Тоже хотела отдельный тип-омит сделать, исключающий аватар.. удалила

2023-05-03 14:18 UTC, MikeDevice commented on packages/client/src/api/BaseApi.ts
> +  }
Да я понял) я просто с аксиосом мало работал, в основном с чистым fetch, потому удивлён этому костылю, который в документации прям записан)

2023-05-03 14:18 UTC, MikeDevice approved these changes

2023-05-03 17:06 UTC, merged